const ContextData = {
    "1": {
        "id": 1,
        "name": "Get List of Cars",
        "role": "Your customer is",
        "context": "You are a knowledge assistant with access to the following GraphQL schema and data. Always try to answer based on this context:",
        "query": "query getCars{cars{id name model manufacturer year}}",
        "schema": "{\"types\":[{\"kind\":\"OBJECT\",\"name\":\"Car\",\"fields\":[{\"name\":\"id\",\"type\":\"Int\",\"description\":\"Unique identifier for the car\",\"dependency\":\"AuthenticationService, ValidationService\",\"apiUsed\":\"mock API: /api/id\",\"mockData\":[1,2,3,4,5],\"mockApiEndpoint\":\"/api/id\"},{\"name\":\"name\",\"type\":\"String\",\"description\":\"Car name\",\"dependency\":\"MashingService, ValidationService\",\"apiUsed\":\"mock API: /api/name\",\"mockData\":[\"Model S\",\"Civic\",\"Corolla\",\"Mustang\",\"Wrangler\"],\"mockApiEndpoint\":\"/api/name\"},{\"name\":\"model\",\"type\":\"String\",\"description\":\"Car model\",\"dependency\":\"MashingService, OrderService\",\"apiUsed\":\"mock API: /api/model\",\"mockData\":[\"Electric Sedan\",\"Sedan\",\"Sedan\",\"Sports Car\",\"SUV\"],\"mockApiEndpoint\":\"/api/model\"},{\"name\":\"manufacturer\",\"type\":\"String\",\"description\":\"Car manufacturer\",\"dependency\":\"OrderService, PaymentService\",\"apiUsed\":\"mock API: /api/manufacturer\",\"mockData\":[\"Tesla\",\"Honda\",\"Toyota\",\"Ford\",\"Jeep\"],\"mockApiEndpoint\":\"/api/manufacturer\"},{\"name\":\"year\",\"type\":\"Int\",\"description\":\"Year of manufacturing\",\"dependency\":\"AuthenticationService, PaymentService\",\"apiUsed\":\"mock API: /api/year\",\"mockData\":[2022,2020,2021,2023,2022],\"mockApiEndpoint\":\"/api/year\"}]}]}",
        "mockApis": "{\"/api/id\":{\"response\":[1,2,3,4,5],\"status\":200},\"/api/name\":{\"response\":[\"Model S\",\"Civic\",\"Corolla\",\"Mustang\",\"Wrangler\"],\"status\":200},\"/api/model\":{\"response\":[\"Electric Sedan\",\"Sedan\",\"Sedan\",\"Sports Car\",\"SUV\"],\"status\":200},\"/api/manufacturer\":{\"response\":[\"Tesla\",\"Honda\",\"Toyota\",\"Ford\",\"Jeep\"],\"status\":200},\"/api/year\":{\"response\":[2022,2020,2021,2023,2022],\"status\":200}}"
    },
    "2": {
        "id": 2,
        "name": "Get List of Planes",
        "role": "Your customer is",
        "context": "You are a knowledge assistant with access to the following GraphQL schema and data. Always try to answer based on this context:",
        "query": "query getCars{cars{id name model manufacturer year}}",
        "schema": "{\"types\":[{\"kind\":\"OBJECT\",\"name\":\"Car\",\"fields\":[{\"name\":\"id\",\"type\":\"Int\",\"description\":\"Unique identifier for the car\",\"dependency\":\"AuthenticationService, ValidationService\",\"apiUsed\":\"mock API: /api/id\",\"mockData\":[1,2,3,4,5],\"mockApiEndpoint\":\"/api/id\"},{\"name\":\"name\",\"type\":\"String\",\"description\":\"Car name\",\"dependency\":\"MashingService, ValidationService\",\"apiUsed\":\"mock API: /api/name\",\"mockData\":[\"Model S\",\"Civic\",\"Corolla\",\"Mustang\",\"Wrangler\"],\"mockApiEndpoint\":\"/api/name\"},{\"name\":\"model\",\"type\":\"String\",\"description\":\"Car model\",\"dependency\":\"MashingService, OrderService\",\"apiUsed\":\"mock API: /api/model\",\"mockData\":[\"Electric Sedan\",\"Sedan\",\"Sedan\",\"Sports Car\",\"SUV\"],\"mockApiEndpoint\":\"/api/model\"},{\"name\":\"manufacturer\",\"type\":\"String\",\"description\":\"Car manufacturer\",\"dependency\":\"OrderService, PaymentService\",\"apiUsed\":\"mock API: /api/manufacturer\",\"mockData\":[\"Tesla\",\"Honda\",\"Toyota\",\"Ford\",\"Jeep\"],\"mockApiEndpoint\":\"/api/manufacturer\"},{\"name\":\"year\",\"type\":\"Int\",\"description\":\"Year of manufacturing\",\"dependency\":\"AuthenticationService, PaymentService\",\"apiUsed\":\"mock API: /api/year\",\"mockData\":[2022,2020,2021,2023,2022],\"mockApiEndpoint\":\"/api/year\"}]}]}",
        "mockApis": "{\"/api/id\":{\"response\":[1,2,3,4,5],\"status\":200},\"/api/name\":{\"response\":[\"Model S\",\"Civic\",\"Corolla\",\"Mustang\",\"Wrangler\"],\"status\":200},\"/api/model\":{\"response\":[\"Electric Sedan\",\"Sedan\",\"Sedan\",\"Sports Car\",\"SUV\"],\"status\":200},\"/api/manufacturer\":{\"response\":[\"Tesla\",\"Honda\",\"Toyota\",\"Ford\",\"Jeep\"],\"status\":200},\"/api/year\":{\"response\":[2022,2020,2021,2023,2022],\"status\":200}}"
    },
    "3": {
        "id": 3,
        "name": "Get List of Cycle",
        "role": "Your customer is",
        "context": "You are a knowledge assistant with access to the following GraphQL schema and data. Always try to answer based on this context:",
        "query": "query getCars{cars{id name model manufacturer year}}",
        "schema": "{\"types\":[{\"kind\":\"OBJECT\",\"name\":\"Car\",\"fields\":[{\"name\":\"id\",\"type\":\"Int\",\"description\":\"Unique identifier for the car\",\"dependency\":\"AuthenticationService, ValidationService\",\"apiUsed\":\"mock API: /api/id\",\"mockData\":[1,2,3,4,5],\"mockApiEndpoint\":\"/api/id\"},{\"name\":\"name\",\"type\":\"String\",\"description\":\"Car name\",\"dependency\":\"MashingService, ValidationService\",\"apiUsed\":\"mock API: /api/name\",\"mockData\":[\"Model S\",\"Civic\",\"Corolla\",\"Mustang\",\"Wrangler\"],\"mockApiEndpoint\":\"/api/name\"},{\"name\":\"model\",\"type\":\"String\",\"description\":\"Car model\",\"dependency\":\"MashingService, OrderService\",\"apiUsed\":\"mock API: /api/model\",\"mockData\":[\"Electric Sedan\",\"Sedan\",\"Sedan\",\"Sports Car\",\"SUV\"],\"mockApiEndpoint\":\"/api/model\"},{\"name\":\"manufacturer\",\"type\":\"String\",\"description\":\"Car manufacturer\",\"dependency\":\"OrderService, PaymentService\",\"apiUsed\":\"mock API: /api/manufacturer\",\"mockData\":[\"Tesla\",\"Honda\",\"Toyota\",\"Ford\",\"Jeep\"],\"mockApiEndpoint\":\"/api/manufacturer\"},{\"name\":\"year\",\"type\":\"Int\",\"description\":\"Year of manufacturing\",\"dependency\":\"AuthenticationService, PaymentService\",\"apiUsed\":\"mock API: /api/year\",\"mockData\":[2022,2020,2021,2023,2022],\"mockApiEndpoint\":\"/api/year\"}]}]}",
        "mockApis": "{\"/api/id\":{\"response\":[1,2,3,4,5],\"status\":200},\"/api/name\":{\"response\":[\"Model S\",\"Civic\",\"Corolla\",\"Mustang\",\"Wrangler\"],\"status\":200},\"/api/model\":{\"response\":[\"Electric Sedan\",\"Sedan\",\"Sedan\",\"Sports Car\",\"SUV\"],\"status\":200},\"/api/manufacturer\":{\"response\":[\"Tesla\",\"Honda\",\"Toyota\",\"Ford\",\"Jeep\"],\"status\":200},\"/api/year\":{\"response\":[2022,2020,2021,2023,2022],\"status\":200}}"
    },
    "4": {
        "id": 4,
        "name": "Get List of Bikes",
        "role": "Your customer is",
        "context": "You are a knowledge assistant with access to the following GraphQL schema and data. Always try to answer based on this context:",
        "query": "query getCars{cars{id name model manufacturer year}}",
        "schema": "{\"types\":[{\"kind\":\"OBJECT\",\"name\":\"Car\",\"fields\":[{\"name\":\"id\",\"type\":\"Int\",\"description\":\"Unique identifier for the car\",\"dependency\":\"AuthenticationService, ValidationService\",\"apiUsed\":\"mock API: /api/id\",\"mockData\":[1,2,3,4,5],\"mockApiEndpoint\":\"/api/id\"},{\"name\":\"name\",\"type\":\"String\",\"description\":\"Car name\",\"dependency\":\"MashingService, ValidationService\",\"apiUsed\":\"mock API: /api/name\",\"mockData\":[\"Model S\",\"Civic\",\"Corolla\",\"Mustang\",\"Wrangler\"],\"mockApiEndpoint\":\"/api/name\"},{\"name\":\"model\",\"type\":\"String\",\"description\":\"Car model\",\"dependency\":\"MashingService, OrderService\",\"apiUsed\":\"mock API: /api/model\",\"mockData\":[\"Electric Sedan\",\"Sedan\",\"Sedan\",\"Sports Car\",\"SUV\"],\"mockApiEndpoint\":\"/api/model\"},{\"name\":\"manufacturer\",\"type\":\"String\",\"description\":\"Car manufacturer\",\"dependency\":\"OrderService, PaymentService\",\"apiUsed\":\"mock API: /api/manufacturer\",\"mockData\":[\"Tesla\",\"Honda\",\"Toyota\",\"Ford\",\"Jeep\"],\"mockApiEndpoint\":\"/api/manufacturer\"},{\"name\":\"year\",\"type\":\"Int\",\"description\":\"Year of manufacturing\",\"dependency\":\"AuthenticationService, PaymentService\",\"apiUsed\":\"mock API: /api/year\",\"mockData\":[2022,2020,2021,2023,2022],\"mockApiEndpoint\":\"/api/year\"}]}]}",
        "mockApis": "{\"/api/id\":{\"response\":[1,2,3,4,5],\"status\":200},\"/api/name\":{\"response\":[\"Model S\",\"Civic\",\"Corolla\",\"Mustang\",\"Wrangler\"],\"status\":200},\"/api/model\":{\"response\":[\"Electric Sedan\",\"Sedan\",\"Sedan\",\"Sports Car\",\"SUV\"],\"status\":200},\"/api/manufacturer\":{\"response\":[\"Tesla\",\"Honda\",\"Toyota\",\"Ford\",\"Jeep\"],\"status\":200},\"/api/year\":{\"response\":[2022,2020,2021,2023,2022],\"status\":200}}"
    },
    "5": {
        "id": 5,
        "name": "Get List of Activa",
        "role": "Your customer is",
        "context": "You are a knowledge assistant with access to the following GraphQL schema and data. Always try to answer based on this context:",
        "query": "query getCars{cars{id name model manufacturer year}}",
        "schema": "{\"types\":[{\"kind\":\"OBJECT\",\"name\":\"Car\",\"fields\":[{\"name\":\"id\",\"type\":\"Int\",\"description\":\"Unique identifier for the car\",\"dependency\":\"AuthenticationService, ValidationService\",\"apiUsed\":\"mock API: /api/id\",\"mockData\":[1,2,3,4,5],\"mockApiEndpoint\":\"/api/id\"},{\"name\":\"name\",\"type\":\"String\",\"description\":\"Car name\",\"dependency\":\"MashingService, ValidationService\",\"apiUsed\":\"mock API: /api/name\",\"mockData\":[\"Model S\",\"Civic\",\"Corolla\",\"Mustang\",\"Wrangler\"],\"mockApiEndpoint\":\"/api/name\"},{\"name\":\"model\",\"type\":\"String\",\"description\":\"Car model\",\"dependency\":\"MashingService, OrderService\",\"apiUsed\":\"mock API: /api/model\",\"mockData\":[\"Electric Sedan\",\"Sedan\",\"Sedan\",\"Sports Car\",\"SUV\"],\"mockApiEndpoint\":\"/api/model\"},{\"name\":\"manufacturer\",\"type\":\"String\",\"description\":\"Car manufacturer\",\"dependency\":\"OrderService, PaymentService\",\"apiUsed\":\"mock API: /api/manufacturer\",\"mockData\":[\"Tesla\",\"Honda\",\"Toyota\",\"Ford\",\"Jeep\"],\"mockApiEndpoint\":\"/api/manufacturer\"},{\"name\":\"year\",\"type\":\"Int\",\"description\":\"Year of manufacturing\",\"dependency\":\"AuthenticationService, PaymentService\",\"apiUsed\":\"mock API: /api/year\",\"mockData\":[2022,2020,2021,2023,2022],\"mockApiEndpoint\":\"/api/year\"}]}]}",
        "mockApis": "{\"/api/id\":{\"response\":[1,2,3,4,5],\"status\":200},\"/api/name\":{\"response\":[\"Model S\",\"Civic\",\"Corolla\",\"Mustang\",\"Wrangler\"],\"status\":200},\"/api/model\":{\"response\":[\"Electric Sedan\",\"Sedan\",\"Sedan\",\"Sports Car\",\"SUV\"],\"status\":200},\"/api/manufacturer\":{\"response\":[\"Tesla\",\"Honda\",\"Toyota\",\"Ford\",\"Jeep\"],\"status\":200},\"/api/year\":{\"response\":[2022,2020,2021,2023,2022],\"status\":200}}"
    }
};

module.exports = ContextData